name: CMake

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=${{github.workspace}}/build/bin

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Compress
      run: 7z a -tzip ${{github.workspace}}/bin/${{github.ref_name}}-${{matrix.os}}.zip ${{github.workspace}}/build/bin/*

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: ${{github.ref_name}}-${{matrix.os}}.zip
        path: ${{github.workspace}}/bin/${{github.ref_name}}-${{matrix.os}}.zip

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download
      uses: actions/download-artifact@v2
      with:
        path: ${{github.workspace}}/bin

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        fail_on_unmatched_files: true
        files: ${{github.workspace}}/bin/**/*.zip

    #- name: Test
      #working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      #run: ctest -C ${{env.BUILD_TYPE}}

